# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb10ac5e570468858aeac02ccafb512326f0a851dc4a4395d6a69d07d3d46978d68f487da6cb6c58f871308cbdc951b4d84bedf76671574b0d2e6ec30f6c8f88

test:
  secret_key_base: cd8a880c46a63be205433c9a605422b2f3df57e163eb17e5bdaba438ce739264ba4f81321d0d962e68a29acb19baade87962434464361d38d5cd4ab3240b03ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
